/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-22 at 10:26:21 UTC 
 * Modify at your own risk.
 */

package com.appspot.lunch__mates__endpoints.lunchmates.model;

/**
 * Model definition for Meeting.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the lunchmates. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Meeting extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String created;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("earliest_possible_start")
  private java.lang.String earliestPossibleStart;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("latest_possible_start")
  private java.lang.String latestPossibleStart;

  /**
   * ProtoRPC container for GeoPt instances. Attributes: lat: Float; The latitude of the point. lon:
   * Float; The longitude of the point.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GeoPtMessage location;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("owner_id") @com.google.api.client.json.JsonString
  private java.lang.Long ownerId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> tags;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String topic;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("venue_forsquare_id")
  private java.lang.String venueForsquareId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreated() {
    return created;
  }

  /**
   * @param created created or {@code null} for none
   */
  public Meeting setCreated(java.lang.String created) {
    this.created = created;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEarliestPossibleStart() {
    return earliestPossibleStart;
  }

  /**
   * @param earliestPossibleStart earliestPossibleStart or {@code null} for none
   */
  public Meeting setEarliestPossibleStart(java.lang.String earliestPossibleStart) {
    this.earliestPossibleStart = earliestPossibleStart;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Meeting setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLatestPossibleStart() {
    return latestPossibleStart;
  }

  /**
   * @param latestPossibleStart latestPossibleStart or {@code null} for none
   */
  public Meeting setLatestPossibleStart(java.lang.String latestPossibleStart) {
    this.latestPossibleStart = latestPossibleStart;
    return this;
  }

  /**
   * ProtoRPC container for GeoPt instances. Attributes: lat: Float; The latitude of the point. lon:
   * Float; The longitude of the point.
   * @return value or {@code null} for none
   */
  public GeoPtMessage getLocation() {
    return location;
  }

  /**
   * ProtoRPC container for GeoPt instances. Attributes: lat: Float; The latitude of the point. lon:
   * Float; The longitude of the point.
   * @param location location or {@code null} for none
   */
  public Meeting setLocation(GeoPtMessage location) {
    this.location = location;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOwnerId() {
    return ownerId;
  }

  /**
   * @param ownerId ownerId or {@code null} for none
   */
  public Meeting setOwnerId(java.lang.Long ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getTags() {
    return tags;
  }

  /**
   * @param tags tags or {@code null} for none
   */
  public Meeting setTags(java.util.List<java.lang.String> tags) {
    this.tags = tags;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTopic() {
    return topic;
  }

  /**
   * @param topic topic or {@code null} for none
   */
  public Meeting setTopic(java.lang.String topic) {
    this.topic = topic;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public Meeting setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getVenueForsquareId() {
    return venueForsquareId;
  }

  /**
   * @param venueForsquareId venueForsquareId or {@code null} for none
   */
  public Meeting setVenueForsquareId(java.lang.String venueForsquareId) {
    this.venueForsquareId = venueForsquareId;
    return this;
  }

  @Override
  public Meeting set(String fieldName, Object value) {
    return (Meeting) super.set(fieldName, value);
  }

  @Override
  public Meeting clone() {
    return (Meeting) super.clone();
  }

}
